### PR TITLE
basic override: override prototype

### PR DESCRIPTION
**Pull request by fippo**
overrides the prototype correctly

### CODE REVIEW

**Comment by fippo** [comment]
I was somewhat surprised how this was done. I would have expected a 
```
newPeerConnection = ...
newPeerConnection.prototype = origPeerConnection.prototype
```
but rtcstats didn't do that either. This should work but is waaaaay to smart. I don't like smart code.

**Comment by ggarber** [comment]
I'm not sure why we need to override the prototype here but I believe you.     @juandebravo  sits next to the JS oracle so maybe he can invoke him at some point.   Merging this change by now.

**Comment by juandebravo** [comment]
umm I don't see the added value neither (hello @drslump), but I realised we're breaking this static method:

```javascript
RTCPeerConnection.generateCertificate()
```

**Comment by drslump** [comment]
For normal use there is no need for wiring the prototype, the `newPeerConnection` function is a constructor with its own prototype chain but since it ends with `return new origPeerConnection(...)` it won't matter, the instance and prototype from `newPeerConnection` will never be used.

The reason I imagine the original prototype is wired that way must be to allow *calling statically* an *instance method*, which is a weird use case but I guess it's better to have it covered:

```js
RTCPeerConnection.prototype.close.call(myConnInstance)
```

Note though that with the current implementation the following, which is probably more important, *won't work*:

```js
let pc = new RTCPeerConnection()
assert( pc instanceof RTCPeerConnection )  // pc is actually an instance of origPeerConnection
```

A possible solution to the above is to replace the `return new origPeerConnection` with something like:

```js
origPeerConnect.call(this, config, constraints)
return this  // implicit
```

Assuming browsers expose `RTCPeerConnection` without hacks it should solve the `instanceof` problem. In general I think a better way to augment a constructor is to follow this pattern:

```js
let origCtor = ...

function newCtor () {
  ... your setup logic ...
  origCtor.apply(this, arguments)
  ... your post initialization logic ...
}

// Wire the original prototype chain but don't hide the additional constructor
// it's an extra hop but not a perf concern and it allows `instanceof` and static
// access to prototype members.
newCtor.prototype = Object.create(origCtor.prototype)
newCtor.prototype.constructor = newCtor
```

For instance this is how the constructor would look like for the `getStats` example:

```js
    var newPeerConnection = function(config, constraints) {
        origPeerConnection.apply(this, arguments);
        
        // We can use the instance normally inside the constructor
        this.getStats().then((stats) => {
            // collect stats
        });
    }
```

About the faulty `generateCertificate`, the problem there is that it's an static method (property of the constructor) so it's not inherited from the prototype. In that case there is a need to *copy* the static members to the new constructor. This generic snippet should cover those cases (although it doesn't always work for browser exposed interfaces, ie Array):

```js
Object.keys(origCtor).forEach( x => newCtor[x] = origCtor[x] )
```

**Comment by fippo** [comment]
we could simply say "use rtcstats.js and modify..." ;-)

**Pull request merged**
